.gitignore, functions/index.js, functions/package-lock.json, package.json, pnpm-lock.yaml, src/hooks/index.ts, src/pages/index.tsx
=> add:google認証の追加

codegen.ts, graphql.schema.json, package.json, pnpm-lock.yaml, src/components/MeetingLog.tsx, src/components/Speech.tsx, src/generates/graphql.ts, src/graphql/mutation/updateMeeting.graphql, src/graphql/subscription/refreshLog.graphql, src/hooks/index.ts, src/libs/createClient.ts, src/pages/_app.tsx, src/pages/index.tsx, src/types/index.ts
=> add:音声認識および取得した音声の共有を実装 #4

src/components/CreateRoom.tsx, src/components/DeleteRoom.tsx, src/generates/graphql.ts, src/graphql/mutation/createRoom.graphql, src/graphql/mutation/deleteRoom.graphql, src/pages/index.tsx
=> add:ルーム削除機能 追加機能の実装 #11

package.json, pnpm-lock.yaml, src/components/CreateRoom.tsx, src/components/DeleteRoom.tsx, src/components/MeetingLog.tsx, src/generates/graphql.ts, src/graphql/mutation/createRoom.graphql, src/hooks/index.ts, src/pages/_app.tsx, src/pages/index.tsx, src/state/meetingAtom.ts, src/state/userAtom.ts
=> add:recoilによる状態保持の追加 #13

graphql.schema.json, src/components/CreateRoom.tsx, src/components/Layout.tsx, src/components/LogModal.tsx, src/generates/graphql.ts, src/graphql/mutation/createRoom.graphql, src/graphql/mutation/deleteRoom.graphql, src/pages/_app.tsx, src/state/logModalAtom.ts, src/types/index.ts
=> add:ログようのモーダルの追加 #14

src/libs/theme.ts, src/pages/_app.tsx
=> add:createThemeを追加 #18

functions/index.js
=> add:ログインした時に取得するユーザーの情報を増加 #20

graphql.schema.json, src/components/InviteUserForm.tsx, src/generates/graphql.ts, src/graphql/mutation/inviteMeetingUser.graphql, src/pages/index.tsx, src/styles/globals.css
=> add:userをemailで招待できるように実装 #22

graphql.schema.json, src/components/CreateRoom.tsx, src/components/DeleteRoom.tsx, src/components/InviteUserForm.tsx, src/components/Layout.tsx, src/components/LoadingModal.tsx, src/generates/graphql.ts, src/hooks/index.ts, src/state/loadingModalAtom.ts, src/types/index.ts
=> add:loadingようのモーダルの作成 それに伴うhooksの追加 #25

graphql.schema.json, next.config.js, src/components/CreateRoom.tsx, src/components/InviteUserForm.tsx, src/components/MeetingLog.tsx, src/components/MeetingUsers.tsx, src/components/Speech.tsx, src/generates/graphql.ts, src/graphql/mutation/inviteMeetingUser.graphql, src/graphql/query/getLog.graphql, src/hooks/index.ts, src/pages/meeting.tsx
=> add:meetingページの実装 #31

src/components/CreateRoom.tsx, src/components/DeleteRoom.tsx, src/components/InviteUserForm.tsx, src/components/Speech.tsx, src/hooks/index.ts
=> change:logModalを使う部分をカスタムフックに変更 #32

src/hooks/index.ts, src/pages/meeting.tsx, src/state/userAtom.ts
=> add:userのログインを保持するカスタムフックを実装 #36

graphql.schema.json, src/components/ChangeUserNameForm.tsx, src/generates/graphql.ts, src/graphql/mutation/changeUserName.graphql, src/graphql/query/getUserName.graphql, src/hooks/index.ts
=> add:userNameを変更するフォームの作成 #34

src/components/Common/ChangeUserNameForm.tsx, src/components/Room/CreateRoom.tsx, src/components/Room/InviteUserForm.tsx, src/hooks/client.ts, src/libs/createClient.ts, src/pages/_app.tsx, src/pages/meeting.tsx
=> add:ユーザーのpermissionを追加 #44

graphql.schema.json, src/components/Meeting/MeetingUsers.tsx, src/components/Meeting/Speech.tsx, src/components/Room/CreateRoom.tsx, src/components/Room/InvitedRoomList.tsx, src/generates/graphql.ts, src/graphql/query/getInvitedMeeting.graphql, src/hooks/server.ts, src/libs/index.ts, src/pages/meeting/[meetingId].tsx, src/pages/meeting/index.tsx
=> add:招待されているミーティングの一覧表示 #46

src/pages/index.tsx
=> add:トップページの作成 #41

src/libs/theme.ts
=> add:テーマカラー #50

src/components/Common/Header.tsx, src/components/Common/Layout.tsx, src/components/Common/SideBar.tsx, src/components/Meeting/MeetingDocuments.tsx, src/components/Room/CreateRoom.tsx, src/components/Room/InvitedRoomList.tsx, src/hooks/client.ts, src/hooks/server.ts, src/state/userAtom.ts
=> add:headerでstateによる表示変更 #52

graphql.schema.json, src/components/Room/CreateRoom.tsx, src/components/Room/InvitedRoomList.tsx, src/generates/graphql.ts, src/graphql/mutation/createRoom.graphql, src/graphql/query/getInvitedMeeting.graphql, src/graphql/query/getMeetingDocuments.graphql, src/pages/meeting/index.tsx
=> add:議事録にタイトルを追加 #56

src/pages/index.tsx
=> fix:keyを追加 #60

src/components/Room/CloseRoom.tsx, src/components/Room/CreateRoom.tsx
=> fix:undefinedを招待したと出るバグを修正 #62

src/components/Room/CloseRoom.tsx, src/components/Room/InviteUserForm.tsx, src/components/Room/LeaveRoom.tsx, src/generates/graphql.ts, src/graphql/query/getLog.graphql, src/hooks/server.ts, src/pages/meeting/[meetingId].tsx
=> add:ownerかそれ以外かで一部要素の可視を変更 #64

src/components/Common/ChangeUserNameForm.tsx, src/components/Common/HamburgerMenu.tsx, src/components/Common/Header.tsx, src/components/Meeting/MeetingUsers.tsx, src/generates/graphql.ts, src/graphql/subscription/refreshLog.graphql, src/hooks/client.ts, src/hooks/server.ts, src/pages/meeting/[meetingId].tsx
=> add:logout機能の追加 #63

src/components/Room/InvitedRoomList.tsx
=> change:自分が作成した部屋かどうかで可視を変更 #70

package.json, pnpm-lock.yaml, src/components/Common/Header.tsx, src/components/Common/QrCode.tsx, src/hooks/server.ts, src/pages/index.tsx, src/pages/invitation.tsx, src/pages/meeting/[meetingId].tsx
=> add:qrコードのよる招待の追加 #69

package.json, pnpm-lock.yaml, src/components/Meeting/MarkDownPreview.tsx, src/components/Meeting/MeetingLog.tsx, src/components/Meeting/SaveFile.tsx, src/generates/graphql.ts, src/graphql/query/getLog.graphql, src/graphql/subscription/refreshLog.graphql, src/hooks/server.ts, src/pages/meeting/[meetingId].tsx, src/types/index.ts
=> add:ファイルとして保存できるように実装 #27

src/components/Common/QrCode.tsx, src/components/Meeting/Speech.tsx, src/hooks/server.ts, src/pages/invitation.tsx
=> fix:qr code #76

pnpm-lock.yaml, src/components/Meeting/MeetingDocuments.tsx, src/components/Meeting/Speech.tsx, src/components/Room/CreateRoom.tsx, src/components/Room/InvitedRoomList.tsx, src/pages/meeting/index.tsx
=> add:ミーティングの装飾 #54
